### ISSUE TITLE
Write a java program called Marks

### ISSUE THREAD

**Issue by TyCo86** [java-tester-x/javaexercises#1]
Write a program in Java called Marks, which prompts user for the number of marks, reads it from the keyboard, and saves it in an int variable called numOfMarks. It then prompts user for the marks and saves them in an int array called marks.  Your program shall check that the marks value is between 0 and 100 and the number of marks is between 1 to 30. The program should display number of marks that are more than 50. An example of output is shown below:

Enter the number of marks: 2
Enter  marks 1: 112
Invalid marks.. try again...
Enter  marks 1: 49
Enter marks 2: 60
Number of marks more than 50 is 1

Note: This program can be written in a structured way.

**Comment by java-tester-x** [comment]
Done.
